project_id = "hsylqytpylzwzoultptj"

[functions.get-cep]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.fetch-products]
verify_jwt = false

[functions.fetch-categories]
verify_jwt = false
